//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.01 at 08:55:49 AM CST 
//


package com.consiti.h2h.beans;

import java.math.BigInteger;
import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CUSTOMER_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BANK_BATCH_ID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="BATCH_TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UPLOAD_DATE" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="APPLICATION_DATE" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="NUMBER_OF_TRANSACTIONS" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="TOTAL_AMOUNT" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TRANSACTIONS">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TRANSACTION">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="TXN_REFERENCE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="DEBIT_ACCOUNT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="CREDIT_ACCOUNT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="AMOUNT" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="DOCUMENT_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ERROR_CODE" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="ERROR_MESSAGE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "customerid",
    "bankbatchid",
    "batchtype",
    "uploaddate",
    "applicationdate",
    "numberoftransactions",
    "totalamount",
    "status",
    "transactions"
})
@XmlRootElement(name = "consultaDetalleLote")
public class ConsultaDetalleLote {

    @XmlElement(name = "CUSTOMER_ID", required = true)
    protected String customerid;
    @XmlElement(name = "BANK_BATCH_ID", required = true)
    protected BigInteger bankbatchid;
    @XmlElement(name = "BATCH_TYPE", required = true)
    protected String batchtype;
    @XmlElement(name = "UPLOAD_DATE", required = true)
    @XmlSchemaType(name = "date")
    private Date uploaddate;
    @XmlElement(name = "APPLICATION_DATE", required = true)
    @XmlSchemaType(name = "date")
    private Date applicationdate;
    @XmlElement(name = "NUMBER_OF_TRANSACTIONS", required = true)
    protected BigInteger numberoftransactions;
    @XmlElement(name = "TOTAL_AMOUNT", required = true)
    protected BigInteger totalamount;
    @XmlElement(name = "STATUS", required = true)
    protected String status;
    @XmlElement(name = "TRANSACTIONS", required = true)
    protected ConsultaDetalleLote.TRANSACTIONS transactions;

    /**
     * Gets the value of the customerid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTOMERID() {
        return customerid;
    }

    /**
     * Sets the value of the customerid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTOMERID(String value) {
        this.customerid = value;
    }

    /**
     * Gets the value of the bankbatchid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBANKBATCHID() {
        return bankbatchid;
    }

    /**
     * Sets the value of the bankbatchid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBANKBATCHID(BigInteger value) {
        this.bankbatchid = value;
    }

    /**
     * Gets the value of the batchtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBATCHTYPE() {
        return batchtype;
    }

    /**
     * Sets the value of the batchtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBATCHTYPE(String value) {
        this.batchtype = value;
    }
    /**
     * Gets the value of the numberoftransactions property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNUMBEROFTRANSACTIONS() {
        return numberoftransactions;
    }

    /**
     * Sets the value of the numberoftransactions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNUMBEROFTRANSACTIONS(BigInteger value) {
        this.numberoftransactions = value;
    }

    /**
     * Gets the value of the totalamount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTOTALAMOUNT() {
        return totalamount;
    }

    /**
     * Sets the value of the totalamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTOTALAMOUNT(BigInteger value) {
        this.totalamount = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATUS() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATUS(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the transactions property.
     * 
     * @return
     *     possible object is
     *     {@link ConsultaDetalleLote.TRANSACTIONS }
     *     
     */
    public ConsultaDetalleLote.TRANSACTIONS getTRANSACTIONS() {
        return transactions;
    }

    /**
     * Sets the value of the transactions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsultaDetalleLote.TRANSACTIONS }
     *     
     */
    public void setTRANSACTIONS(ConsultaDetalleLote.TRANSACTIONS value) {
        this.transactions = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TRANSACTION">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="TXN_REFERENCE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="DEBIT_ACCOUNT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="CREDIT_ACCOUNT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="AMOUNT" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="DOCUMENT_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ERROR_CODE" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="ERROR_MESSAGE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transaction"
    })
    public static class TRANSACTIONS {

        @XmlElement(name = "TRANSACTION", required = true)
        protected ConsultaDetalleLote.TRANSACTIONS.TRANSACTION transaction;

        /**
         * Gets the value of the transaction property.
         * 
         * @return
         *     possible object is
         *     {@link ConsultaDetalleLote.TRANSACTIONS.TRANSACTION }
         *     
         */
        public ConsultaDetalleLote.TRANSACTIONS.TRANSACTION getTRANSACTION() {
            return transaction;
        }

        /**
         * Sets the value of the transaction property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConsultaDetalleLote.TRANSACTIONS.TRANSACTION }
         *     
         */
        public void setTRANSACTION(ConsultaDetalleLote.TRANSACTIONS.TRANSACTION value) {
            this.transaction = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="TXN_REFERENCE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="DEBIT_ACCOUNT" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="CREDIT_ACCOUNT" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="AMOUNT" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="DOCUMENT_NUMBER" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ERROR_CODE" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="ERROR_MESSAGE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "txnreference",
            "debitaccount",
            "creditaccount",
            "amount",
            "documentnumber",
            "status",
            "errorcode",
            "errormessage"
        })
        public static class TRANSACTION {

            @XmlElement(name = "ID", required = true)
            protected BigInteger id;
            @XmlElement(name = "TXN_REFERENCE", required = true)
            protected String txnreference;
            @XmlElement(name = "DEBIT_ACCOUNT", required = true)
            protected String debitaccount;
            @XmlElement(name = "CREDIT_ACCOUNT", required = true)
            protected String creditaccount;
            @XmlElement(name = "AMOUNT", required = true)
            protected BigInteger amount;
            @XmlElement(name = "DOCUMENT_NUMBER", required = true)
            protected String documentnumber;
            @XmlElement(name = "STATUS", required = true)
            protected String status;
            @XmlElement(name = "ERROR_CODE", required = true)
            protected BigInteger errorcode;
            @XmlElement(name = "ERROR_MESSAGE", required = true)
            protected String errormessage;

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getID() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setID(BigInteger value) {
                this.id = value;
            }

            /**
             * Gets the value of the txnreference property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTXNREFERENCE() {
                return txnreference;
            }

            /**
             * Sets the value of the txnreference property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTXNREFERENCE(String value) {
                this.txnreference = value;
            }

            /**
             * Gets the value of the debitaccount property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDEBITACCOUNT() {
                return debitaccount;
            }

            /**
             * Sets the value of the debitaccount property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDEBITACCOUNT(String value) {
                this.debitaccount = value;
            }

            /**
             * Gets the value of the creditaccount property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCREDITACCOUNT() {
                return creditaccount;
            }

            /**
             * Sets the value of the creditaccount property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCREDITACCOUNT(String value) {
                this.creditaccount = value;
            }

            /**
             * Gets the value of the amount property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getAMOUNT() {
                return amount;
            }

            /**
             * Sets the value of the amount property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setAMOUNT(BigInteger value) {
                this.amount = value;
            }

            /**
             * Gets the value of the documentnumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDOCUMENTNUMBER() {
                return documentnumber;
            }

            /**
             * Sets the value of the documentnumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDOCUMENTNUMBER(String value) {
                this.documentnumber = value;
            }

            /**
             * Gets the value of the status property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSTATUS() {
                return status;
            }

            /**
             * Sets the value of the status property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSTATUS(String value) {
                this.status = value;
            }

            /**
             * Gets the value of the errorcode property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getERRORCODE() {
                return errorcode;
            }

            /**
             * Sets the value of the errorcode property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setERRORCODE(BigInteger value) {
                this.errorcode = value;
            }

            /**
             * Gets the value of the errormessage property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getERRORMESSAGE() {
                return errormessage;
            }

            /**
             * Sets the value of the errormessage property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setERRORMESSAGE(String value) {
                this.errormessage = value;
            }

        }

    }

    public Date getUploaddate() {
        return uploaddate;
    }

    public void setUploaddate(Date uploaddate) {
        this.uploaddate = uploaddate;
    }

    public Date getApplicationdate() {
        return applicationdate;
    }

    public void setApplicationdate(Date applicationdate) {
        this.applicationdate = applicationdate;
    }

}
