//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.10.01 at 09:49:24 AM CST 
//


package com.consiti.h2h.beans;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GLOBAL_ID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="CUSTOMER_ID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="USERNAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BATCHES">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="BATCH">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CUSTOMER_BATCH_ID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="TYPE" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="DATA_STRUCTURE">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="VALIDATIONS">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="DEBIT_ACCT_BALANCE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="DEBIT_ACCT_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="NUMBER_OF_TRANSACTIONS" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                                                 &lt;element name="TOTAL_AMOUNT" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="FIELDS">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="FIELD" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="DELIMITER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="TRANSACTIONS">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="TRANSACTION" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "globalid",
    "customerid",
    "username",
    "batches"
})
@XmlRootElement(name = "pagosMasivos")
public class PagosMasivos {

    @XmlElement(name = "GLOBAL_ID", required = true)
    protected BigInteger globalid;
    @XmlElement(name = "CUSTOMER_ID", required = true)
    protected BigInteger customerid;
    @XmlElement(name = "USERNAME", required = true)
    protected String username;
    @XmlElement(name = "BATCHES", required = true)
    protected PagosMasivos.BATCHES batches;

    /**
     * Gets the value of the globalid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGLOBALID() {
        return globalid;
    }

    /**
     * Sets the value of the globalid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGLOBALID(BigInteger value) {
        this.globalid = value;
    }

    /**
     * Gets the value of the customerid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCUSTOMERID() {
        return customerid;
    }

    /**
     * Sets the value of the customerid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCUSTOMERID(BigInteger value) {
        this.customerid = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSERNAME() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSERNAME(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the batches property.
     * 
     * @return
     *     possible object is
     *     {@link PagosMasivos.BATCHES }
     *     
     */
    public PagosMasivos.BATCHES getBATCHES() {
        return batches;
    }

    /**
     * Sets the value of the batches property.
     * 
     * @param value
     *     allowed object is
     *     {@link PagosMasivos.BATCHES }
     *     
     */
    public void setBATCHES(PagosMasivos.BATCHES value) {
        this.batches = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="BATCH">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="CUSTOMER_BATCH_ID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="TYPE" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="DATA_STRUCTURE">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="VALIDATIONS">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="DEBIT_ACCT_BALANCE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="DEBIT_ACCT_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="NUMBER_OF_TRANSACTIONS" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                                       &lt;element name="TOTAL_AMOUNT" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="FIELDS">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="FIELD" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="DELIMITER" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="TRANSACTIONS">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="TRANSACTION" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "batch"
    })
    public static class BATCHES {

        @XmlElement(name = "BATCH", required = true)
        protected PagosMasivos.BATCHES.BATCH batch;

        /**
         * Gets the value of the batch property.
         * 
         * @return
         *     possible object is
         *     {@link PagosMasivos.BATCHES.BATCH }
         *     
         */
        public PagosMasivos.BATCHES.BATCH getBATCH() {
            return batch;
        }

        /**
         * Sets the value of the batch property.
         * 
         * @param value
         *     allowed object is
         *     {@link PagosMasivos.BATCHES.BATCH }
         *     
         */
        public void setBATCH(PagosMasivos.BATCHES.BATCH value) {
            this.batch = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="CUSTOMER_BATCH_ID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="TYPE" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="DATA_STRUCTURE">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="VALIDATIONS">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="DEBIT_ACCT_BALANCE" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="DEBIT_ACCT_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="NUMBER_OF_TRANSACTIONS" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *                             &lt;element name="TOTAL_AMOUNT" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="FIELDS">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="FIELD" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="DELIMITER" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="TRANSACTIONS">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="TRANSACTION" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "customerbatchid",
            "type",
            "datastructure",
            "transactions"
        })
        public static class BATCH {

            @XmlElement(name = "CUSTOMER_BATCH_ID", required = true)
            protected BigInteger customerbatchid;
            @XmlElement(name = "TYPE", required = true)
            protected BigInteger type;
            @XmlElement(name = "DATA_STRUCTURE", required = true)
            protected PagosMasivos.BATCHES.BATCH.DATASTRUCTURE datastructure;
            @XmlElement(name = "TRANSACTIONS", required = true)
            protected PagosMasivos.BATCHES.BATCH.TRANSACTIONS transactions;

            /**
             * Gets the value of the customerbatchid property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getCUSTOMERBATCHID() {
                return customerbatchid;
            }

            /**
             * Sets the value of the customerbatchid property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setCUSTOMERBATCHID(BigInteger value) {
                this.customerbatchid = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getTYPE() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setTYPE(BigInteger value) {
                this.type = value;
            }

            /**
             * Gets the value of the datastructure property.
             * 
             * @return
             *     possible object is
             *     {@link PagosMasivos.BATCHES.BATCH.DATASTRUCTURE }
             *     
             */
            public PagosMasivos.BATCHES.BATCH.DATASTRUCTURE getDATASTRUCTURE() {
                return datastructure;
            }

            /**
             * Sets the value of the datastructure property.
             * 
             * @param value
             *     allowed object is
             *     {@link PagosMasivos.BATCHES.BATCH.DATASTRUCTURE }
             *     
             */
            public void setDATASTRUCTURE(PagosMasivos.BATCHES.BATCH.DATASTRUCTURE value) {
                this.datastructure = value;
            }

            /**
             * Gets the value of the transactions property.
             * 
             * @return
             *     possible object is
             *     {@link PagosMasivos.BATCHES.BATCH.TRANSACTIONS }
             *     
             */
            public PagosMasivos.BATCHES.BATCH.TRANSACTIONS getTRANSACTIONS() {
                return transactions;
            }

            /**
             * Sets the value of the transactions property.
             * 
             * @param value
             *     allowed object is
             *     {@link PagosMasivos.BATCHES.BATCH.TRANSACTIONS }
             *     
             */
            public void setTRANSACTIONS(PagosMasivos.BATCHES.BATCH.TRANSACTIONS value) {
                this.transactions = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="VALIDATIONS">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="DEBIT_ACCT_BALANCE" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="DEBIT_ACCT_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="NUMBER_OF_TRANSACTIONS" type="{http://www.w3.org/2001/XMLSchema}integer"/>
             *                   &lt;element name="TOTAL_AMOUNT" type="{http://www.w3.org/2001/XMLSchema}integer"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="FIELDS">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="FIELD" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="DELIMITER" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "validations",
                "fields",
                "delimiter"
            })
            public static class DATASTRUCTURE {

                @XmlElement(name = "VALIDATIONS", required = true)
                protected PagosMasivos.BATCHES.BATCH.DATASTRUCTURE.VALIDATIONS validations;
                @XmlElement(name = "FIELDS", required = true)
                protected PagosMasivos.BATCHES.BATCH.DATASTRUCTURE.FIELDS fields;
                @XmlElement(name = "DELIMITER", required = true)
                protected String delimiter;

                /**
                 * Gets the value of the validations property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link PagosMasivos.BATCHES.BATCH.DATASTRUCTURE.VALIDATIONS }
                 *     
                 */
                public PagosMasivos.BATCHES.BATCH.DATASTRUCTURE.VALIDATIONS getVALIDATIONS() {
                    return validations;
                }

                /**
                 * Sets the value of the validations property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link PagosMasivos.BATCHES.BATCH.DATASTRUCTURE.VALIDATIONS }
                 *     
                 */
                public void setVALIDATIONS(PagosMasivos.BATCHES.BATCH.DATASTRUCTURE.VALIDATIONS value) {
                    this.validations = value;
                }

                /**
                 * Gets the value of the fields property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link PagosMasivos.BATCHES.BATCH.DATASTRUCTURE.FIELDS }
                 *     
                 */
                public PagosMasivos.BATCHES.BATCH.DATASTRUCTURE.FIELDS getFIELDS() {
                    return fields;
                }

                /**
                 * Sets the value of the fields property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link PagosMasivos.BATCHES.BATCH.DATASTRUCTURE.FIELDS }
                 *     
                 */
                public void setFIELDS(PagosMasivos.BATCHES.BATCH.DATASTRUCTURE.FIELDS value) {
                    this.fields = value;
                }

                /**
                 * Gets the value of the delimiter property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDELIMITER() {
                    return delimiter;
                }

                /**
                 * Sets the value of the delimiter property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDELIMITER(String value) {
                    this.delimiter = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="FIELD" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "field"
                })
                public static class FIELDS {

                    @XmlElement(name = "FIELD", required = true)
                    protected List<String> field;

                    /**
                     * Gets the value of the field property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the field property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getFIELD().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link String }
                     * 
                     * 
                     * @return 
                     */
                    public List<String> getFIELD() {
                        if (field == null) {
                            field = new ArrayList<>();
                        }
                        return this.field;
                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="DEBIT_ACCT_BALANCE" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="DEBIT_ACCT_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="NUMBER_OF_TRANSACTIONS" type="{http://www.w3.org/2001/XMLSchema}integer"/>
                 *         &lt;element name="TOTAL_AMOUNT" type="{http://www.w3.org/2001/XMLSchema}integer"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "debitacctbalance",
                    "debitacctstatus",
                    "numberoftransactions",
                    "totalamount"
                })
                public static class VALIDATIONS {

                    @XmlElement(name = "DEBIT_ACCT_BALANCE", required = true)
                    protected String debitacctbalance;
                    @XmlElement(name = "DEBIT_ACCT_STATUS", required = true)
                    protected String debitacctstatus;
                    @XmlElement(name = "NUMBER_OF_TRANSACTIONS", required = true)
                    protected BigInteger numberoftransactions;
                    @XmlElement(name = "TOTAL_AMOUNT", required = true)
                    protected BigInteger totalamount;

                    /**
                     * Gets the value of the debitacctbalance property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getDEBITACCTBALANCE() {
                        return debitacctbalance;
                    }

                    /**
                     * Sets the value of the debitacctbalance property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setDEBITACCTBALANCE(String value) {
                        this.debitacctbalance = value;
                    }

                    /**
                     * Gets the value of the debitacctstatus property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getDEBITACCTSTATUS() {
                        return debitacctstatus;
                    }

                    /**
                     * Sets the value of the debitacctstatus property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setDEBITACCTSTATUS(String value) {
                        this.debitacctstatus = value;
                    }

                    /**
                     * Gets the value of the numberoftransactions property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigInteger }
                     *     
                     */
                    public BigInteger getNUMBEROFTRANSACTIONS() {
                        return numberoftransactions;
                    }

                    /**
                     * Sets the value of the numberoftransactions property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigInteger }
                     *     
                     */
                    public void setNUMBEROFTRANSACTIONS(BigInteger value) {
                        this.numberoftransactions = value;
                    }

                    /**
                     * Gets the value of the totalamount property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigInteger }
                     *     
                     */
                    public BigInteger getTOTALAMOUNT() {
                        return totalamount;
                    }

                    /**
                     * Sets the value of the totalamount property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigInteger }
                     *     
                     */
                    public void setTOTALAMOUNT(BigInteger value) {
                        this.totalamount = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="TRANSACTION" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "transaction"
            })
            public static class TRANSACTIONS {

                @XmlElement(name = "TRANSACTION", required = true)
                protected List<String> transaction;

                /**
                 * Gets the value of the transaction property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the transaction property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getTRANSACTION().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 * @return 
                 */
                public List<String> getTRANSACTION() {
                    if (transaction == null) {
                        transaction = new ArrayList<>();
                    }
                    return this.transaction;
                }

            }

        }

    }

}
